### ISSUE TITLE
Интегрировать последние фиксы из upstream

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/utransnet-ui#2]
Источник - [UTCORE/БЧ, #4/2018](https://github.com/u-transnet/info/issues/61)

[upstream](https://github.com/bitshares/bitshares-ui) уже содержит какое-то количество фиксов, которые нам надо учиться интегрировать в наш форк кошелька.

**Comment by ghost** [comment]
Пройтись по всем нашим зависимостям faucet, wallet, node, python-bitshares, python-graphene и затащить апстримы, скооперироваться с @EvgeniyPolyakov касаемо wallet, задеплоить новую версию кошелька.

Часть вещей была проделана еще 24-25.01.18 в рамках докера

BLOCK #23849909
map-13
150UTDEV.SKILL
До вечера 26.01.18

**Comment by ghost** [comment]
### [u-tech-bitshares](https://github.com/u-tech-bitshares)
- #### [bitshares faucet](https://github.com/u-tech-bitshares/faucet)
  - [~master~](https://github.com/u-tech-bitshares/faucet/pull/3)
- #### [bitshares wallet](https://github.com/u-tech-bitshares/bitshares-ui)
  - [~master~](https://github.com/u-tech-bitshares/bitshares-ui/pull/4)
  - [~staging~](https://github.com/u-tech-bitshares/bitshares-ui/pull/3)

Выкатил [тут](https://transnet.tech:10443)

**Comment by ghost** [comment]
### [u-transnet](https://github.com/u-transnet)
- [transnet-core](https://github.com/u-transnet/utransnet-core)
  - [~master~](https://github.com/u-transnet/utransnet-core/pull/2)
  Пришлось править немного докер [тут](https://github.com/u-transnet/dockerfiles/pull/5)
  [Поднял](https://transnet.space:10443) новую версию ноды
- [python-graphenelib](https://github.com/u-transnet/python-graphenelib)
  - master актуален
  - [~develop~](https://github.com/u-transnet/python-graphenelib/pull/6)
- [python-transnet](https://github.com/u-transnet/python-utransnet)
  - master пока нельзя подтягивать, будут проблемы с faucet
  - [~develop~](https://github.com/u-transnet/python-utransnet/pull/3)
- [faucet](https://github.com/u-transnet/utransnet-faucet)
  - [~master~](https://github.com/u-transnet/utransnet-faucet/pull/3)
- [bitsharesjs-ws](https://github.com/u-transnet/bitsharesjs-ws)
  - master актуален
  @EvgeniyPolyakov просьба почистить ненужные уже ветки
- [bitsharesjs](https://github.com/u-transnet/bitsharesjs)
  - master актуален
  @EvgeniyPolyakov просьба почистить ненужные уже ветки
- [wallet](https://github.com/u-transnet/utransnet-ui)
  - [~master~](https://github.com/u-transnet/utransnet-ui/pull/4)
  - [~staging~](https://github.com/u-transnet/utransnet-ui/pull/5)
  - [~utt_nodes~](https://github.com/u-transnet/utransnet-ui/pull/6)
  @EvgeniyPolyakov просьба посмотреть конфликты и зарезолвить merge, на странице реквеста есть мануал (use command line to ...) как это делать

**Comment by ghost** [comment]
@kkrupovich 
Результаты в двух предыдущих каментах.
По моей части все готово, я все сделал, можно смотреть, теперь дело за @EvgeniyPolyakov.
Ему нужно зарезолвить конфликты и прочее, сделать сборочку, попросить меня ее выложить, почистить ветки.
@EvgeniyPolyakov в комментариях выше есть подсказки, куда смотреть. @EvgeniyPolyakov, скилуйся и действуй.

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23929648

ПЕРЕВОД |  
От | eugene-polyakov
Кому | utd-web
Количество | 70.00000 UTDEV.SKILL

До вечера 29.01.18

**Comment by ghost** [comment]
@kkrupovich 
https://github.com/u-transnet/dockerfiles/pull/7
https://github.com/u-transnet/dockerfiles/pull/8
Обновленный wallet выложили [тут](https://transnet.space:10443/).
Можно закрывать.

**Comment by EvgeniyPolyakov** [comment]
Пересоберу билд - в выложенном в сохраненных настройках не стоит тема оформления UT по умолчанию - на нее надо переключаться. Но в принципе все ок, "Можно закрывать 2".

UPD

Тема стоит. Подтягиваются более глобальные настройки с графена похоже. Удалю выбор альтеративных схем оформления, оставлю только кастомизированную. 

done https://github.com/u-transnet/dockerfiles/commit/6cd8ff7c5d8a999d3333c5e38e32acf4aabb4d07

**Comment by ghost** [comment]
@kkrupovich @EvgeniyPolyakov закрываем
https://github.com/u-transnet/dockerfiles/pull/9
https://github.com/u-transnet/dockerfiles/pull/10
https://transnet.space:10443/
Не забываем почистить куки или в инкогнито смотреть

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23970757

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

@EvgeniyPolyakov 
BLOCK #23970796

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 75.00000 UTDEV
