### ISSUE TITLE
Визуальная кастомизация bitshares-ui под стиль компании

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [u-transnet/utransnet-ui#3]
Создания css-темы оформления UT-theme для визуального отделения кошелька проекта от проектов, основанных на том же UI

**Comment by EvgeniyPolyakov** [comment]
От | eugene-polyakov
Кому | utd-web
Количество | 80.00000 UTDEV.SKILL

до 22.01.18

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 

BLOCK #23760385

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 80.00000 UTDEV

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov а есть какие-то пуллреквесты, на которые можно сослаться из этой задачи?

**Comment by EvgeniyPolyakov** [comment]
@kkrupovich Вот ссылка на коммит https://github.com/u-transnet/utransnet-ui/commit/d2549b5e6b2e7264e214cb67763033c8ffc3074a

Добавленно лого, новая тема + в дефолтных настройках установленна тема компании по-умолчанию etc
