### ISSUE TITLE
Добавить сохранение кастомных данных в профиль Bitsharejs

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [u-transnet/utransnet-ui#7]
Разобраться в общей структуре модуля.

Реализуем добавление кастомных настроек и их сохранение в профиль пользователя для последующего использования:

- Токен git
- Уровень скилла
- Адрес отправки скилла

**Comment by EvgeniyPolyakov** [comment]
БЛОК #24369840

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

До утра 15.02.18

**Comment by EvgeniyPolyakov** [comment]
Сделано:

знакомство с архитектурой

добавление кастомных настроек:

- Закладка UT Settings
- имя в Git
- токен в Git
- имя в Jira
- токен в Jira
- имя получателя скилла

https://github.com/u-transnet/utransnet-ui/commit/6cc5433e44b0be99079078d00095f2dca60a4c60 

![2018-02-19 13 54 03](https://user-images.githubusercontent.com/13783084/36369605-9b39ccbe-157d-11e8-8aba-e2ac1ca5f7d7.jpg)

Сдвиг по дате - были выходные + брал еще один, так как почти весь скилл выработан.

Можно закрывать

**Comment by cptn-solo** [comment]
По большому счету в рамках этой задачи мы лишь поняли как расширять настройки и получать к ним доступ. Сами по себе настройки, скорее всего, не актуальные, надо будет понять что действительно мы должны хранить в этих настройках @EvgeniyPolyakov @netral23 , предлагаю продоложать в отдельной задаче `TBD`

BLOCK #24561248

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 140.00000 UTDEV
